USE [master]
GO

/****** Object:  Database [GrBritainRadel]    Script Date: 15.09.2022 14:53:01 ******/
CREATE DATABASE [GrBritainRadel]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GrBritainRadel', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\GrBritainRadel.mdf' , SIZE = 4160KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'GrBritainRadel_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\GrBritainRadel_log.ldf' , SIZE = 1040KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GrBritainRadel].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GrBritainRadel] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GrBritainRadel] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GrBritainRadel] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GrBritainRadel] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GrBritainRadel] SET ARITHABORT OFF 
GO

ALTER DATABASE [GrBritainRadel] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [GrBritainRadel] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GrBritainRadel] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GrBritainRadel] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GrBritainRadel] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GrBritainRadel] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GrBritainRadel] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GrBritainRadel] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GrBritainRadel] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GrBritainRadel] SET  ENABLE_BROKER 
GO

ALTER DATABASE [GrBritainRadel] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GrBritainRadel] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GrBritainRadel] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GrBritainRadel] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GrBritainRadel] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GrBritainRadel] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GrBritainRadel] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GrBritainRadel] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GrBritainRadel] SET  MULTI_USER 
GO

ALTER DATABASE [GrBritainRadel] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GrBritainRadel] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GrBritainRadel] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GrBritainRadel] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [GrBritainRadel] SET  READ_WRITE 
GO

